# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddInfo(object):
    def setupUi(self, AddInfo):
        AddInfo.setObjectName("AddInfo")
        AddInfo.resize(659, 160)
        self.label = QtWidgets.QLabel(AddInfo)
        self.label.setGeometry(QtCore.QRect(30, 10, 31, 31))
        self.label.setObjectName("label")
        self.ID = QtWidgets.QPlainTextEdit(AddInfo)
        self.ID.setGeometry(QtCore.QRect(60, 10, 111, 31))
        self.ID.setPlainText("")
        self.ID.setObjectName("ID")
        self.label_2 = QtWidgets.QLabel(AddInfo)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 31, 31))
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QPlainTextEdit(AddInfo)
        self.name.setGeometry(QtCore.QRect(260, 10, 111, 31))
        self.name.setPlainText("")
        self.name.setObjectName("name")
        self.label_3 = QtWidgets.QLabel(AddInfo)
        self.label_3.setGeometry(QtCore.QRect(230, 60, 31, 31))
        self.label_3.setObjectName("label_3")
        self.phone = QtWidgets.QPlainTextEdit(AddInfo)
        self.phone.setGeometry(QtCore.QRect(260, 60, 111, 31))
        self.phone.setPlainText("")
        self.phone.setObjectName("phone")
        self.label_4 = QtWidgets.QLabel(AddInfo)
        self.label_4.setGeometry(QtCore.QRect(30, 60, 31, 31))
        self.label_4.setObjectName("label_4")
        self.address = QtWidgets.QPlainTextEdit(AddInfo)
        self.address.setGeometry(QtCore.QRect(60, 110, 311, 31))
        self.address.setPlainText("")
        self.address.setObjectName("address")
        self.birthday = QtWidgets.QPlainTextEdit(AddInfo)
        self.birthday.setGeometry(QtCore.QRect(60, 60, 111, 31))
        self.birthday.setPlainText("")
        self.birthday.setObjectName("birthday")
        self.label_5 = QtWidgets.QLabel(AddInfo)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 31, 31))
        self.label_5.setObjectName("label_5")
        self.mail = QtWidgets.QPlainTextEdit(AddInfo)
        self.mail.setGeometry(QtCore.QRect(470, 60, 131, 31))
        self.mail.setPlainText("")
        self.mail.setObjectName("mail")
        self.label_6 = QtWidgets.QLabel(AddInfo)
        self.label_6.setGeometry(QtCore.QRect(420, 60, 51, 31))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(AddInfo)
        self.pushButton.setGeometry(QtCore.QRect(500, 110, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.sex = QtWidgets.QPlainTextEdit(AddInfo)
        self.sex.setGeometry(QtCore.QRect(490, 10, 111, 31))
        self.sex.setPlainText("")
        self.sex.setObjectName("name_2")
        self.label_7 = QtWidgets.QLabel(AddInfo)
        self.label_7.setGeometry(QtCore.QRect(460, 10, 31, 31))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(AddInfo)
        QtCore.QMetaObject.connectSlotsByName(AddInfo)

    def retranslateUi(self, AddInfo):
        _translate = QtCore.QCoreApplication.translate
        AddInfo.setWindowTitle(_translate("AddInfo", "增加学生信息"))
        self.label.setText(_translate("AddInfo", "学号"))
        self.label_2.setText(_translate("AddInfo", "姓名"))
        self.label_3.setText(_translate("AddInfo", "电话"))
        self.label_4.setText(_translate("AddInfo", "生日"))
        self.label_5.setText(_translate("AddInfo", "地址"))
        self.label_6.setText(_translate("AddInfo", "电子邮箱"))
        self.pushButton.setText(_translate("AddInfo", "添加"))
        self.label_7.setText(_translate("AddInfo", "性别"))

    def get_inset(self):
        id = self.ID.toPlainText()
        name = self.name.toPlainText()
        sex = self.sex.toPlainText()
        phone = self.phone.toPlainText()
        birthday = self.birthday.toPlainText()
        address = self.address.toPlainText()
        email = self.mail.toPlainText()
        info = [id, name, sex, phone, birthday, address, email]
        return info

    def clear_text(self):
        _translate = QtCore.QCoreApplication.translate
        self.ID.setPlainText(_translate("UpdateInfo", ""))
        self.name.setPlainText(_translate("UpdateInfo", ""))
        self.sex.setPlainText(_translate("UpdateInfo", ""))
        self.phone.setPlainText(_translate("UpdateInfo", ""))
        self.birthday.setPlainText(_translate("UpdateInfo", ""))
        self.address.setPlainText(_translate("UpdateInfo", ""))
        self.mail.setPlainText(_translate("UpdateInfo", ""))
