# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Adduser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_AddUser(object):
    def setupUi(self, AddUser):
        AddUser.setObjectName("AddUser")
        AddUser.resize(362, 114)
        self.pushButton = QtWidgets.QPushButton(AddUser)
        self.pushButton.setGeometry(QtCore.QRect(250, 80, 91, 21))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(AddUser)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 31))
        self.label.setObjectName("label")
        self.passwd = QtWidgets.QPlainTextEdit(AddUser)
        self.passwd.setGeometry(QtCore.QRect(240, 20, 111, 31))
        self.passwd.setPlainText("")
        self.passwd.setObjectName("passwd")
        self.ID = QtWidgets.QPlainTextEdit(AddUser)
        self.ID.setGeometry(QtCore.QRect(60, 20, 111, 31))
        self.ID.setPlainText("")
        self.ID.setObjectName("ID")
        self.label_2 = QtWidgets.QLabel(AddUser)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 31, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(AddUser)
        QtCore.QMetaObject.connectSlotsByName(AddUser)

    def retranslateUi(self, AddUser):
        _translate = QtCore.QCoreApplication.translate
        AddUser.setWindowTitle(_translate("AddUser", "添加用户"))
        self.pushButton.setText(_translate("AddUser", "添加用户"))
        self.label.setText(_translate("AddUser", "用户名"))
        self.label_2.setText(_translate("AddUser", "密码"))

    def clear(self):
        _translate = QtCore.QCoreApplication.translate
        self.ID.setPlainText(_translate("UpdateInfo", ""))
        self.passwd.setPlainText(_translate("UpdateInfo", ""))