# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangePass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangePass(object):
    def setupUi(self, ChangePass):
        ChangePass.setObjectName("ChangePass")
        ChangePass.resize(375, 125)
        self.label = QtWidgets.QLabel(ChangePass)
        self.label.setGeometry(QtCore.QRect(20, 20, 41, 31))
        self.label.setObjectName("label")
        self.user = QtWidgets.QPlainTextEdit(ChangePass)
        self.user.setEnabled(False)
        self.user.setGeometry(QtCore.QRect(70, 20, 111, 31))
        self.user.setPlainText("")
        self.user.setObjectName("user")
        self.passwd = QtWidgets.QPlainTextEdit(ChangePass)
        self.passwd.setGeometry(QtCore.QRect(250, 20, 111, 31))
        self.passwd.setPlainText("")
        self.passwd.setOverwriteMode(False)
        self.passwd.setObjectName("passwd")
        self.pushButton = QtWidgets.QPushButton(ChangePass)
        self.pushButton.setGeometry(QtCore.QRect(260, 80, 91, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(ChangePass)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 31, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(ChangePass)
        QtCore.QMetaObject.connectSlotsByName(ChangePass)

    def retranslateUi(self, ChangePass):
        _translate = QtCore.QCoreApplication.translate
        ChangePass.setWindowTitle(_translate("ChangePass", "修改密码"))
        self.label.setText(_translate("ChangePass", "用户名"))
        self.pushButton.setText(_translate("ChangePass", "修改用户"))
        self.label_2.setText(_translate("ChangePass", "密码"))

