# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView, QAbstractItemView, QTableView

from src.sql import db


class Ui_Manager(object):
    def setupUi(self, Manager):
        Manager.setObjectName("Manager")
        Manager.setEnabled(True)
        Manager.resize(956, 723)
        Manager.setMinimumSize(QtCore.QSize(956, 723))
        self.label = QtWidgets.QLabel(Manager)
        self.label.setGeometry(QtCore.QRect(10, 440, 31, 31))
        self.label.setObjectName("label")
        self.Edit_id = QtWidgets.QTextEdit(Manager)
        self.Edit_id.setGeometry(QtCore.QRect(50, 440, 91, 31))
        self.Edit_id.setObjectName("Edit_id")
        self.label_2 = QtWidgets.QLabel(Manager)
        self.label_2.setGeometry(QtCore.QRect(10, 480, 31, 31))
        self.label_2.setObjectName("label_2")
        self.Edit_name = QtWidgets.QTextEdit(Manager)
        self.Edit_name.setGeometry(QtCore.QRect(50, 480, 91, 31))
        self.Edit_name.setObjectName("Edit_name")
        self.label_3 = QtWidgets.QLabel(Manager)
        self.label_3.setGeometry(QtCore.QRect(10, 520, 31, 31))
        self.label_3.setObjectName("label_3")
        self.Edit_phone = QtWidgets.QTextEdit(Manager)
        self.Edit_phone.setGeometry(QtCore.QRect(50, 520, 91, 31))
        self.Edit_phone.setObjectName("Edit_phone")
        self.Button_find = QtWidgets.QPushButton(Manager)
        self.Button_find.setGeometry(QtCore.QRect(50, 610, 75, 23))
        self.Button_find.setObjectName("Button_find")
        self.Button_add_student = QtWidgets.QPushButton(Manager)
        self.Button_add_student.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.Button_add_student.setObjectName("Button_add_student")
        self.Button_update = QtWidgets.QPushButton(Manager)
        self.Button_update.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.Button_update.setObjectName("Button_update")
        self.Button_delete = QtWidgets.QPushButton(Manager)
        self.Button_delete.setGeometry(QtCore.QRect(20, 110, 111, 31))
        self.Button_delete.setObjectName("Button_delete")
        self.Button_change_passwd = QtWidgets.QPushButton(Manager)
        self.Button_change_passwd.setGeometry(QtCore.QRect(20, 240, 111, 31))
        self.Button_change_passwd.setObjectName("Button_change_passwd")
        self.Button_add_user = QtWidgets.QPushButton(Manager)
        self.Button_add_user.setGeometry(QtCore.QRect(20, 200, 111, 31))
        self.Button_add_user.setObjectName("Button_add_user")
        self.Sinfo = QtWidgets.QTableWidget(Manager)
        self.Sinfo.setGeometry(QtCore.QRect(170, 10, 781, 711))
        self.Sinfo.setObjectName("Sinfo")
        self.Sinfo.setColumnCount(7)
        self.Sinfo.setRowCount(0)
        self.Sinfo.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)  # 所有列自动拉伸，充满界面
        self.Sinfo.setSelectionMode(QAbstractItemView.SingleSelection)  # 设置只能选中一行
        self.Sinfo.setEditTriggers(QTableView.NoEditTriggers)  # 不可编辑
        self.Sinfo.setSelectionBehavior(QAbstractItemView.SelectRows)  # 设置只有行选中
        self.Sinfo.resizeColumnsToContents()  # 自适应
        item = QtWidgets.QTableWidgetItem()
        self.Sinfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sinfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sinfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sinfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sinfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sinfo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sinfo.setHorizontalHeaderItem(6, item)
        self.line = QtWidgets.QFrame(Manager)
        self.line.setGeometry(QtCore.QRect(130, 10, 41, 711))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Edit_email = QtWidgets.QTextEdit(Manager)
        self.Edit_email.setGeometry(QtCore.QRect(50, 560, 91, 31))
        self.Edit_email.setObjectName("Edit_email")
        self.label_4 = QtWidgets.QLabel(Manager)
        self.label_4.setGeometry(QtCore.QRect(10, 560, 31, 31))
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(Manager)
        self.line_2.setGeometry(QtCore.QRect(10, 160, 131, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Manager)
        self.line_3.setGeometry(QtCore.QRect(10, 330, 131, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Button_clear = QtWidgets.QPushButton(Manager)
        self.Button_clear.setGeometry(QtCore.QRect(50, 640, 75, 23))
        self.Button_clear.setObjectName("Button_clear")

        # add_windows = AddWindow()
        # self.Button_add_user.clicked.connect(add_windows.show)

        self.retranslateUi(Manager)
        QtCore.QMetaObject.connectSlotsByName(Manager)


    def retranslateUi(self, Manager):
        _translate = QtCore.QCoreApplication.translate
        Manager.setWindowTitle(_translate("Manager", "学生管理系统"))
        self.label.setText(_translate("Manager", "学号"))
        self.label_2.setText(_translate("Manager", "姓名"))
        self.label_3.setText(_translate("Manager", "电话"))
        self.Button_find.setText(_translate("Manager", "查询"))
        self.Button_add_student.setText(_translate("Manager", "添加学生"))
        self.Button_update.setText(_translate("Manager", "修改学生"))
        self.Button_delete.setText(_translate("Manager", "删除学生"))
        self.Button_change_passwd.setText(_translate("Manager", "修改密码"))
        self.Button_add_user.setText(_translate("Manager", "添加用户"))
        item = self.Sinfo.horizontalHeaderItem(0)
        item.setText(_translate("Manager", "学号"))
        item = self.Sinfo.horizontalHeaderItem(1)
        item.setText(_translate("Manager", "姓名"))
        item = self.Sinfo.horizontalHeaderItem(2)
        item.setText(_translate("Manager", "性别"))
        item = self.Sinfo.horizontalHeaderItem(3)
        item.setText(_translate("Manager", "电话"))
        item = self.Sinfo.horizontalHeaderItem(4)
        item.setText(_translate("Manager", "生日"))
        item = self.Sinfo.horizontalHeaderItem(5)
        item.setText(_translate("Manager", "地址"))
        item = self.Sinfo.horizontalHeaderItem(6)
        item.setText(_translate("Manager", "邮箱"))
        self.label_4.setText(_translate("Manager", "邮箱"))
        self.Button_clear.setText(_translate("Manager", "还原"))
        self.set_tree()
        self.Sinfo.selectRow(0)

    def set_tree(self, info=None):
        if not info:
            info = db.get_all_info()
        if info:
            for i in range(len(info)):
                item = info[i]
                row_count = self.Sinfo.rowCount()
                self.Sinfo.insertRow(row_count)

                for j in range(len(item)):
                    insert_info = QtWidgets.QTableWidgetItem(str(info[i][j]))
                    self.Sinfo.setItem(row_count, j, insert_info)

    def chang_tree(self, row: int, info: list):
        for i in range(len(info)):
            insert_info = QtWidgets.QTableWidgetItem(str(info[i]))
            self.Sinfo.setItem(row, i, insert_info)

    def add_tree(self, info: list):
        row_count = self.Sinfo.rowCount()
        self.Sinfo.insertRow(row_count)

        for i in range(len(info)):
            insert_info = QtWidgets.QTableWidgetItem(str(info[i]))
            self.Sinfo.setItem(row_count, i, insert_info)

    def clear_table(self):
        for rowNum in range(0, self.Sinfo.rowCount())[::-1]:
            self.Sinfo.removeRow(rowNum)

    def clear_find(self):
        self.Edit_id.setPlainText("")
        self.Edit_name.setPlainText("")
        self.Edit_phone.setPlainText("")
        self.Edit_email.setPlainText("")

    def recover(self):
        self.clear_table()
        self.set_tree()
        self.clear_find()
